BibCnrs/BibApi

- lib/controller/ebsco/index.js
- lib/controller/ebsco/login.js
- lib/controller/ebsco/profile.js
- lib/models/JanusAccount.js
- lib/queries/janusAccountQueries.js
- migrations/030-janus_account-favorite_domain.psql
- test/mocha/functional/renaterLogin.js
- test/mocha/models/JanusAccount.js
[Trello card](https://trello.com/c/VDeIu3O1/23-2-bibcnrs-en-tant-qu-utilisateur-janus-je-veux-pouvoir-enregistrer-mon-domaine-prefere)
> [RFR] Favorite domain

- lib/controller/ezticket/401.html
- lib/controller/ezticket/index.js
[Trello card](https://trello.com/c/SY5gvbHw/15-0-5-bibcnrs-modifier-le-libelle-des-messages-d-erreur-unauthorized)
> [RFR] Custom messages for ezticket 401 errors

- bin/assignSectionToUnit.js
- bin/commands/assignSectionToUnit.js
- bin/commands/importSectionCN.js
- bin/importSectionCN.js
- lib/models/SectionCN.js
- lib/models/Unit.js
- lib/queries/sectionCNQueries.js
- makefile
follow #141 
Import without info on order, absent from dump
> [RFR] Import section

- docker-compose.dev.yml
- lib/controller/admin/index.js
- lib/controller/admin/janusAccounts.js
- lib/queries/janusAccountQueries.js
[Trello card](https://trello.com/c/pe4lRCPa)
> [RFR] Faster Janus Accounts export

- lib/controller/ebsco/login.js
- test/mocha/functional/renaterLogin.js
[Trello card](https://trello.com/b/AYTD0Z4W)
> [RFR] Ensure we create janus account only when we have all needed data

- lib/controller/ezticket/login.html
> [RFR] update ezticket login with new auth layout

- config/test.js
- docker-compose.test.yml
- lib/controller/ebsco/publicationSearch.js
- lib/services/parsePublicationSearchQuery.js
- test/mocha/services/parsePublicationSearchQuery.js
depends on https://github.com/BibCnrs/EBSCO-widget/pull/171
> [RFR] A2z better sort

- lib/controller/ebsco/domains.js
- test/mocha/functional/domains.js
- test/mocha/services/parsePublicationSearchQuery.js
linked to https://github.com/BibCnrs/EBSCO-widget/pull/177
> [RFR] returns gate with domains name

- migrations/041-table-unit-nb_unit_account-not_null.psql
linked to https://github.com/BibCnrs/BibAdmin/pull/56
> [RFR] add NOT NULL constraint to nb_unit_account

- lib/controller/ezticket/login.html
> Revert "[RFR] fix ezticket form"

- lib/queries/janusAccountQueries.js
- migrations/042-janus_account-first_connexion.psql
- test/mocha/models/JanusAccount.js
linked to https://github.com/BibCnrs/BibAdmin/pull/58
> [RFR] First connect

- lib/controller/admin/index.js
- lib/models/Revue.js
- lib/models/RevueCommunity.js
- lib/queries/communityQueries.js
- lib/queries/revueCommunityQueries.js
- lib/queries/revueQueries.js
- migrations/048-table-revue.psql
- migrations/049-table-revue_community.psql
https://trello.com/c/xXn8RRZg/106-2-option-3-bibcnrs-initialisation-des-ressources-favorites-pour-lutilisateur
> [RFR] add route for Revue (default favourite ressources)

- lib/controller/ebsco/index.js
- lib/controller/ebsco/login.js
- lib/models/Revue.js
- lib/queries/revueQueries.js
- package-lock.json
- package.json
- test/mocha/functional/getLogin.js
- test/mocha/functional/renaterLogin.js
- test/mocha/models/Revue.js
- test/utils/fixtureLoader.js
https://trello.com/c/xXn8RRZg/106-2-option-3-bibcnrs-initialisation-des-ressources-favorites-pour-lutilisateur
> [RFR] Favourite resources

- lib/queries/janusAccountQueries.js
Display more recent account first in similar uid mail alert
> [RFR] order similar uid by last_connexion and uid to have more recent first

- lib/controller/ebsco/favouriteResources.js
- lib/controller/ebsco/index.js
- lib/controller/ebsco/login.js
- lib/models/JanusAccount.js
- lib/queries/janusAccountQueries.js
- migrations/050-janus_account-column-favourite_resources.psql
- test/mocha/functional/getLogin.js
- test/mocha/models/JanusAccount.js
https://trello.com/c/xpvpiT1S/107-1-option-3-bibcnrs-ajout-des-ressources-favorites-par-lutilisateur
> [RFR] Add favourite resources

- lib/models/SectionCN.js
> minor evolution and fix bug

- .travis.yml
- config/default.js
- config/preproduction.js
- config/production.js
- config/test.js
- config/verif.js
- lib/controller/ebsco/articleSearch.js
- lib/services/articleParser.js
- lib/services/searchParser.js
- package-lock.json
- package.json
- test/mocha/functional/articleRetrieve.js
- test/mocha/functional/renaterLogin.js
- test/mocha/models/Community.js
- test/mocha/services/articleParser.js
- test/mocha/services/generateEZTicket.js
- Use unpaywall and generate link with good format
- Updated test folder with last version of linter
- Update last version of babel-eslint
- Update travis at 8.9.1 (same as docker)
> use unpaywall and generate link with good format

- lib/models/SectionCN.js
Corrige le problème d'évitement du test mais à vérifier si on ne casse pas une fonctionnalité côté bibadmin
> remove override section cn test

- lib/utils/postgresCrud.js
For more infos show https://marmelab.com/react-admin/DataProviders.html
> replace `x-total-count` by `content-range`

- lib/controller/ezticket/errorTemplate.js
- lib/controller/ezticket/loginTemplate.js
- lib/services/articleLinkParser.js
> use unpaywall even if there is a open access link

- config/default.js
- lib/controller/ebsco/publicationSearch.js
- lib/services/getInfoFromDOAJ.js
- test/mock/controller/parsedPublicationSearch.json
> Feat: Return isDiamond for publication search

- config/default.js
- docker-compose.dev.yml
- docker-compose.prod.yml
- lib/controller/ebsco/favouriteResources.js
- lib/controller/ebsco/index.js
- lib/controller/ebsco/metadoreSearch.js
- lib/services/metadoreRequest.js
- lib/services/metadoreResultsParser.js
- lib/services/parseSearchQuery.js
> Feat: add Metadore search

- lib/controller/ebsco/index.js
- lib/controller/ebsco/metadoreSearch.js
- lib/services/metadoreResultsParser.js
- lib/services/parseSearchQuery.js
- test/mocha/functional/metadoreSearch.js
- test/mocha/services/metadoreResultsParser.js
- test/mocha/services/parseSearchQuery.js
- test/mocha/services/parsedCovidResult.json
- test/mock/controller/covidResult.json
> Feat: metadore pagination

- lib/services/parseXML.js
> Feat: Catch some html inside xml
